FIREBASE_DATABASE_URL="https://tvguide-48b0a-default-rtdb.europe-west1.firebasedatabase.app/"
FIREBASE_DATABASE_TABLE="backups"
WEB_CLIENT_ID="941960553843-1tdbqvfs29nodkl05fckdecr7rtlj7o7.apps.googleusercontent.com"