[versions]
# plugins
kotlin = "2.3.20"
gradle = "8.12.3"
ksp = "2.3.2"
crashlyticsGradle = "3.0.6"
googleServices = "4.4.4"

# Core
androidx-core = "1.16.0"
androidx-annotation = "1.9.1"
androidx-material = "1.12.0"

timber = "5.0.1"

# Preference
dataStore = "1.1.7"

# Room Database
room = "2.8.4"

# datetime
kotlinx-datetime = "0.6.1"

# Bom
compose-bom = "2026.02.01"
firebase-bom = "34.1.0"

# Compose
compose-activity = "1.10.1"
compose-lifecycle-viewmodel = "2.9.2"
compose-lifecycle-runtime = "2.9.2"

# Compose Navigation
navigation-compose = "2.9.7"

collections-immutable = "0.4.0"

# DI
koin = "4.1.1"

ktor = "3.2.2"

accompanist-permissions = "0.37.3"

# Coroutine
kotlinx-coroutines-core = "1.10.2"
kotlinx-coroutines-android = "1.10.2"

kotlinx-serialization-json = "1.9.0"

# Image
coil = "3.4.0"
coil-compose = "3.4.0"

ksoup = "0.1.5"

# WorkManager
workRuntime = "2.10.2"

# StartUp API
startUp = "1.1.1"

# test libraries
testJunit = "4.13.2"

kotest = "6.1.7"
mockk = "1.14.9"
turbine = "1.2.0"

#review = "2.0.2"
#app-update = "2.1.0"

googleid = "1.1.1"
credentials = "1.5.0"

# android test libraries
testAndroidJunitExt = "1.2.1"
testAndroidEspresso = "3.6.1"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "gradle" }
firebase-crashlitycs = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsGradle" }
gms-googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
#versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
#ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinx-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
# Core
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Preference
dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

# Room Database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

# Coroutine
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }

# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Permissions
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }

# DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
androidx-compose-ui-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "compose-lifecycle-runtime" }
androidx-compose-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-lifecycle-viewmodel" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections-immutable" }

# DI
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }

# Network
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# StartUp
startUp = { module = "androidx.startup:startup-runtime", version.ref = "startUp" }

# Coil
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil-compose" }

# WorkManager
workRuntimeKtx = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }

# Parse
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }

#review = { module = "com.google.android.play:review", version.ref = "review" }
#review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
#
#app-update = { module = "com.google.android.play:app-update", version.ref = "app-update" }
#app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "app-update" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-database = { module = "com.google.firebase:firebase-database" }

googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

# test libraries
testJunit = { module = "junit:junit", version.ref = "testJunit" }
# Kotest
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# android test libraries
testAndroidJunitExt = { module = "androidx.test.ext:junit", version.ref = "testAndroidJunitExt" }
testAndroidEspresso = { module = "androidx.test.espresso:espresso-core", version.ref = "testAndroidEspresso" }

androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }

[bundles]

appLibraries = [
    "androidx-core",
    "timber",
    "androidx-annotation",
    "androidx-material"
]

room = [
    "room-runtime",
    "room-ktx"
]

workManager = [
    "workRuntimeKtx"
]

#playReview = [
#    "review",
#    "review-ktx"
#]
#
#playUpdate = [
#    "app-update",
#    "app-update-ktx"
#]

compose_core = [
    "androidx-compose-activity",
    "androidx-compose-ui-ui",
    "androidx-compose-material3-material3",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-navigation"
]

compose-material-icons = [
    "androidx-compose-material-icons-core",
    "androidx-compose-material-icons-extended"
]

compose_lifecycle = [
    "androidx-compose-lifecycle-runtime",
    "androidx-compose-lifecycle-viewmodel"
]

ktor = [
    "ktor-client-core",
    "ktor-client-okhttp",
    "ktor-client-logging",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-client-encoding"
]

koin = [
    "koin-core",
    "koin-android",
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-workmanager"
]

testAndroid = [
    "testAndroidJunitExt",
    "androidx-compose-ui-test-junit4",
    "testAndroidEspresso"
]

testDebugCompose = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest"
]

firebase = [
    "firebase-analytics",
    "firebase-crashlytics",
    "firebase-auth",
    "firebase-database"
]

kotest = [
    "kotest-runner-junit5",
    "kotest-assertions-core"
]

ksoup = [
    "ksoup",
    "ksoup-network"
]

credentials = [
    "androidx-credentials",
    "androidx-credentials-play-services-auth",
    "googleid"
]

