name: Test debug

# Controls when the workflow will run
on:
 # workflow_call:
  # push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Testing debug variant
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Load Google Service file
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > ./app/google-services.json

      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:${{ secrets.KEYSTORE_PASS }}
          keyPassword:${{ secrets.ALIAS_PASS }}
          keyAlias:${{ secrets.ALIAS }}
          storeFile:${{ vars.KEYSTORE_STORE_FILE_PATH }}
          EOF

      - name: Decode keystore and create jks
        run: echo "${{ secrets.KEYSTORE_JKS }}" | base64 --decode > mvproject.jks

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - testDebug
        run: ./gradlew clean testDebug

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/